config/routes.rb
Rails.application.routes.draw do

  resources :products do
    post 'select_action'
  end
  
  root :to => 'products#index'
  match 'create' => 'products#create', via: :post
  post 'push' => 'products#push', as: :push
  post 'pushall' => 'products#push_all', as: :pushall
  post 'edit_price' => 'products#edit_price', as: :edit_price
  post 'edit_cap' => 'products#edit_cap', as: :edit_cap
  post 'multiply_price' => 'products#multiply_price', as: :multiply_price
  post 'multiply_cap' => 'products#multiply_cap', as: :multiply_cap
  delete 'remove_all' => 'products#remove_all', as: :remove_all
  delete 'imports_remove' => 'products#remove_selected', as: :remove_selected
  
  post 'products/bulkaction'
  get 'my_products' => 'my_products#index', as: :my_products
  delete 'my_products/:id' => 'my_products#destroy', as: :destroy_product

  get '/settings' => 'settings#index'
  put '/settings/edit_markup' => 'settings#edit_markup'
  match '/settings/markup' => 'settings#markup', via: :get

  get 'orders' => 'order#index', as: :orders
  get "/fetch_orders" => "order#from_category", as: :fetch_orders
  put "/edit_note" => "order#edit_note", as: :edit_note
  post "/mark_shipped" => "order#mark_shipped", as: :mark_shipped

  get '/notifications' => 'notification#index', as: :notifications
  match '/notifications/create_notif' => 'notification#create_notif', via: :post
  delete '/notifications/:id' => 'notification#destroy'
  put '/notifications/update_price' => 'notification#update_price', as: :update_price
  
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/controllers/notification_controller.rb
class NotificationController < ApplicationController
  before_action :set_product, only: [:destroy]
  wrap_parameters format: [:json]

  def index
  	#shop_url = "https://2d69dfd97a185d97d49cb4b85de5e76f:1cd78cc392fe8861b891a3f881b3c5d8@gels-store.myshopify.com/admin"
	#ShopifyAPI::Base.site = shop_url
	#shop = ShopifyAPI::Shop.current
  	
  	@notifs = Notification.all.order(created_at: :desc)
  	
  	markup = Markup.find(2)
  	@pmu = markup.price

  end

  def create_notif
    @notif = Notification.create(product_title: params[:product_title],
								product_salePrice: params[:product_salePrice],
								product_originalPrice: params[:product_originalPrice],
								ae_productid: params[:ae_productid],
								shopify_productid: params[:shopify_productid])
  end

  def update_price
  	shop_url = "https://2d69dfd97a185d97d49cb4b85de5e76f:1cd78cc392fe8861b891a3f881b3c5d8@gels-store.myshopify.com/admin"
	ShopifyAPI::Base.site = shop_url
	shop = ShopifyAPI::Shop.current

	price = params[:price]
	cap = params[:compare_at_price]
	i = 0
	product = ShopifyAPI::Product.find(params[:shopify_productid])
	variants = product.variants
	variants.each do |v|
		v.price = price[i]
		v.compare_at_price = cap[i]
		i = i + 1
	end

	product.variants = variants
	product.save
	
	if product.save
		render js: 'toastr.success("Updated successfully")'
	else
		render js: 'toastr.error("Something went wrong.")'
	end

	@notif.destroy

  end

  def destroy
  	@notif.destroy
  end

  private 
  def set_notification
  	@notif = Notification.find(params[:id])
  end
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/views/notification/create_notif.html.erb
<h1>Notification#create_notif</h1>
<p>Find me in app/views/notification/create_notif.html.erb</p>

app/views/notification/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style type="text/css">
		.flex-container {
		    display: -webkit-flex;
		    display: flex;  
		    -webkit-flex-flow: row wrap;
		    flex-flow: row wrap;
		    text-align: center;
		}
		.flex-container > * {
		    padding: 15px;
		    -webkit-flex: 1 100%;
		    flex: 1 100%;
		}
		.right-column {
		    text-align: left;
		}
		header {background: white;color:black;}
		footer {background: #aaa;color:white;}
		.left-column {background:#eee;}
		@media all and (min-width: 768px) {
		    .left-column {text-align:left;-webkit-flex: 1 auto;flex:1 auto;-webkit-order:1;order:1;}
		    .right-column {-webkit-flex:5 0px;flex:5 0px;-webkit-order:2;order:2;}
		    footer {-webkit-order:3;order:3;}
		}

		.btn-remove-notif {
			margin-left: 15px;
			color: #2d2d2d;
		}
		.btn-remove-notif:hover {
			color: #E07A5F;
			background-color: transparent;
		}
		.price, .compare-at-price {
			display: inline-block;
			width: 100px;
		}
		.price-to {
			color: #b7b7b7;
		}
		.data-price-diff {
			color: green;
		}
		.data-price-diff2 {
			color: red;
		}
		.data-product-title {
			height: 50px;
		}
		.data-price-update-option {
			display: inline-block;
		}
	</style>
</head>
<body id="notifs">

	<div class="flex-container">
		
		<header>
		  <h1>Notifications</h1>
		</header>

		<div class="container-fluid text-center" id="page-content"> 
			<div class="row content" style="margin-top: 20px;">
				<div class="col-sm-12 text-left">
					<% @notifs.each do |notif| %>
					<div class="panel-heading">
						<strong><%= notif.created_at %></strong> <!-- notif date -->
					</div>
					<div class="panel-body">
						<div class="rows">
							<div class="col-md-10">
								<span>Product price has changed: </span>
								<a href="">
									<%= notif.product_title %>
								</a>
							</div>
							<div class="col-md-2">
								<button class="btn btn-default prd-view-prices" data-toggle="modal" data-target="#change-price-modal-<%= notif.id %>">View Prices</button>
								<a class="btn-remove-notif">
									<span class="glyphicon glyphicon-remove"></span>
								</a>
							</div>
						</div>
					</div>
					<br/>
						<!-- ***MODAL*** -->
					<div id="change-price-modal-<%= notif.id %>" class="modal">
						<div class="modal-dialog">
							<div class="modal-content" style="width:1100px;">
								<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal">&times;</button>
									<h4 class="modal-title">Change product price</h4>
								</div>
								<div class="modal-body">
									<%= form_tag update_price_path, method: 'put', remote: true do %>
									<div class="data-product-title">
										<span>Product price has changed: </span>
										<a href=""><%= notif.product_title %></a>
									</div>
									<div class="data-table-product-prices">
										<table class="table table-condensed">
											<thead>
												<tr>
													<th>SKU</th>
													<th>Cost Change</th>
													<th>Price Change</th>
													<th>Compare At Price Change</th>
												</tr>
											</thead>
											<tbody>
												<%
													variants = ShopifyAPI::Variant.find(:all, :params => { :product_id => notif.shopify_productid })
													ctr = 0
													newPrice = notif.new_prices.to_f
													newCap = notif.new_cap.to_f	
												%>
												<% variants.each do |item| %>
													<tr>
														<td>
															<div class="data-sku">
																1234ABC-SAMPLESKU-<%= ctr %>
																<%= hidden_field_tag :shopify_productid, notif.shopify_productid %>
															</div>
														</td>
														<td>
															<div class="data-cost">
																$<%= number_with_precision(cost, :precision => 2) %>
																<span class="glyphicon glyphicon-arrow-right price-to"></span>
																<strong>$<%= origPrice %></strong>
																<% if origPrice > salePrice %>
																	<span class="data-price-diff">(+$<%= number_with_precision(origPrice - salePrice, :precision => 2) %>)</span>
																<% elsif origPrice < salePrice %>
																	<span class="data-price-diff-2">(-$<%= number_with_precision(salePrice - origPrice, :precision => 2) %>)</span>
																<% end %>
															</div>
														</td>
														<td>
															<div class="data-price">
																<%= number_to_currency(item.price) %>
																<span class="glyphicon glyphicon-arrow-right price-to"></span>
																<%= text_field_tag "price[]", notif.product_originalPrice, class: 'form-control price' %>
															</div>
														</td>
														<td>
															<div class="data-compare-at-price">
																<%= number_to_currency(item.compare_at_price) %>
																<span class="glyphicon glyphicon-arrow-right price-to"></span>
																<%= text_field_tag "compare_at_price[]", notif.product_originalPrice, class: 'form-control price' %>
															</div>
														</td>
													</tr>
													<% ctr += 1 %>
												<% end %>
											</tbody>
										</table>
									</div>
									<div class="data-price-update-option">
										<button type="button" class="btn btn-default close-modal" data-dismiss="modal">Don't Update</button>
										<!--button type="button" class="btn btn-success close-modal" data-dismiss="modal">Update</button-->
										<%= submit_tag "Update", class: "btn btn-success" %>
									</div>
									<% end %>
								</div>
							</div>
						</div>
					</div> <!-- end of modal -->
					<% end %>
				</div>
			</div>
		</div>

	</div>

</body>
</html>

app/views/notification/update_price.html.erb
<h1>Notification#update_price</h1>
<p>Find me in app/views/notification/update_price.html.erb</p>