config/routes.rb
Rails.application.routes.draw do

  resources :products do
    post 'select_action'
  end
  
  root :to => 'products#index'
  match 'create' => 'products#create', via: :post
  post 'push' => 'products#push', as: :push
  post 'pushall' => 'products#push_all', as: :pushall
  post 'edit_price' => 'products#edit_price', as: :edit_price
  post 'edit_cap' => 'products#edit_cap', as: :edit_cap
  post 'multiply_price' => 'products#multiply_price', as: :multiply_price
  post 'multiply_cap' => 'products#multiply_cap', as: :multiply_cap
  delete 'remove_all' => 'products#remove_all', as: :remove_all
  delete 'imports_remove' => 'products#remove_selected', as: :remove_selected
  
  post 'products/bulkaction'
  get 'my_products' => 'my_products#index', as: :my_products
  delete 'my_products/:id' => 'my_products#destroy', as: :destroy_product

  get '/settings' => 'settings#index'
  put '/settings/edit_markup' => 'settings#edit_markup'
  match '/settings/markup' => 'settings#markup', via: :get

  get 'orders' => 'order#index', as: :orders
  get "/fetch_orders" => "order#from_category", as: :fetch_orders
  put "/edit_note" => "order#edit_note", as: :edit_note
  post "/mark_shipped" => "order#mark_shipped", as: :mark_shipped

  get '/notifications' => 'notification#index', as: :notifications
  match '/notifications/create_notif' => 'notification#create_notif', via: :post
  delete '/notifications/:id' => 'notification#destroy'
  put '/notifications/update_price' => 'notification#update_price', as: :update_price
  
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/my_products_controller.rb
class MyProductsController < ApplicationController
  before_action :set_my_product, only: [:destroy]
  def index
    shop_url = "https://77d56bcf8d3ab9647b85d9030f2b1e1b:22c7a88a600583dea6c121fcb9eb1daf@gels-store.myshopify.com/admin"
    ShopifyAPI::Base.site = shop_url
    shop = ShopifyAPI::Shop.current
    products = ShopifyAPI::Product.find(:all)
    @myproducts = []
    m_namespace = ''
    products.each do |product|
      product.metafields.each do |metafield|
        m_namespace = metafield.namespace
      end
      if m_namespace == 'imported-item'
        @myproducts << product
      end
    end
  end
  
  def destroy
    @my_product.destroy
    respond_to do |format|
      format.html { redirect_to my_products_url, notice: 'My product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_product
      @my_product = ShopifyAPI::Product.find(params[:id])
    end
end

app/helpers/my_products_helper.rb
module MyProductsHelper
end

app/views/my_products/index.html.erb
<html>
  <body>
	    
      <div class="container-fluid text-center" id="page-content">
      	<div class="row content">
          
          <div class="col-md-12 text-left">
            <div><p id="notice"><%= notice %></p></div><br/>
            	<% @myproducts.in_groups_of(2, false).each do |group| %>
		      <div class="row">
			  <% group.each do |product| %>
			    <div class="col-md-6">
				    
			      <div class="panel-heading" style="width: 455px;">
				  <%= link_to "https://2d69dfd97a185d97d49cb4b85de5e76f:1cd78cc392fe8861b891a3f881b3c5d8@gels-store.myshopify.com/admin/products/#{product.id}", method: "get", target: "_blank", class: "btn btn-default", id: "shopify-link" do %>
				    <span class="glyphicon glyphicon-new-window" style="margin-right: 10px;"></span>Open in Shopify
				  <% end %>
				  <div class="btn-group date-range" style="margin-left: 10px;">
				    <a href="#" class="btn btn-default flex-right" id="date-range">Action</a>
				    <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
				    <ul class="dropdown-menu">
				      <li><%= link_to "Delete from Shopify", destroy_product_path(product), method: :delete, data: {confirm: 'Are you sure?'} %></li>
				      <li>Stop Tracking</li>
				      <li>Override this Product</li>
				      <li>Prevent price from auto-updating</li>
				    </ul>
				  </div>
			      </div><!-- end of panel header -->
				    
			      <div class="panel-body" style="width: 455px;">
				<div class="row">
				  <div class="col-md-5">
					  <div class="prd-image"><img src="http://placehold.it/124x124"></div>
				  </div>
				  <div class="col-md-6">
				    <a><%= product.title %></a>
				  </div>
				</div>
			      </div><!-- end of panel body -->
			    </div><!-- end of col -->
		  <% end %>
              </div><!-- end of row -->
	    <br/>
	    <br/>
            <% end %>
            
            
          </div><!-- end of page content -->
          
        </div><!--end of row content-->
      </div><!-- end of container fluid-->
      
  </body>
</html>