config/routes.rb
Rails.application.routes.draw do

  resources :products do
    post 'select_action'
  end
  
  root :to => 'products#index'
  match 'create' => 'products#create', via: :post
  post 'push' => 'products#push', as: :push
  post 'pushall' => 'products#push_all', as: :pushall
  post 'edit_price' => 'products#edit_price', as: :edit_price
  post 'edit_cap' => 'products#edit_cap', as: :edit_cap
  post 'multiply_price' => 'products#multiply_price', as: :multiply_price
  post 'multiply_cap' => 'products#multiply_cap', as: :multiply_cap
  delete 'remove_all' => 'products#remove_all', as: :remove_all
  delete 'imports_remove' => 'products#remove_selected', as: :remove_selected
  
  post 'products/bulkaction'
  get 'my_products' => 'my_products#index', as: :my_products
  delete 'my_products/:id' => 'my_products#destroy', as: :destroy_product

  get '/settings' => 'settings#index'
  put '/settings/edit_markup' => 'settings#edit_markup'
  match '/settings/markup' => 'settings#markup', via: :get

  get 'orders' => 'order#index', as: :orders
  get "/fetch_orders" => "order#from_category", as: :fetch_orders
  put "/edit_note" => "order#edit_note", as: :edit_note
  post "/mark_shipped" => "order#mark_shipped", as: :mark_shipped

  get '/notifications' => 'notification#index', as: :notifications
  match '/notifications/create_notif' => 'notification#create_notif', via: :post
  delete '/notifications/:id' => 'notification#destroy'
  put '/notifications/update_price' => 'notification#update_price', as: :update_price
  
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	def self.search(searchprd)
	  if searchprd
	    where('lower(title) LIKE ?', "%#{searchprd.downcase}%")
	  else
	    all
	  end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  wrap_parameters format: [:json]

  #wrap_parameters format: [:json]
  # GET /products
  # GET /products.json
  def index
    #@products = Product.all
    shop_url = "https://2d69dfd97a185d97d49cb4b85de5e76f:1cd78cc392fe8861b891a3f881b3c5d8@gels-store.myshopify.com/admin"
    ShopifyAPI::Base.site = shop_url
    shop = ShopifyAPI::Shop.current

    @products = Product.search(params[:searchprd])
    #@collects = ShopifyAPI::Collect.find(:all)    #get collection
    @bulkaction = ["Push Selected", "Remove Selected"]
    @ctr = 1
    
    @collections = []
    @cc = ShopifyAPI::CustomCollection.find(:all, :params => {:limit => 250})
    @cc.each do |c|
      @collections << c
    end
    markup = Markup.find(2)
    @price_markup = markup.price
    @price_fm = markup.operator1.to_sym
    @cap_markup = markup.compare_at_price
    @cap_fm = markup.operator2.to_sym
    @capToggle = markup.cap_toggle
  end

  # GET /products/1
  # GET /products/1.json
  def show
    
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.create(title: params[:title],
                              body_html: params[:body_html],
                              product_type: params[:product_type],
                              images: params[:images],
                              vendor: params[:vendor],
                              tags: params[:tags],
                              price: params[:price],
                              price2: params[:price2],
                              compare_at_price: params[:compare_at_price],
                              colors: params[:colors],
                              sizes: params[:sizes],
                              avail_qty: params[:avail_qty],
                              variant_images: params[:variant_images],
                              ae_url: params[:ae_url],
                              mf_key: params[:mf_key])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully imported.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def bulkaction
    
  end
   
  def edit_price
    new_val = '%.2f' % params[:new_val]
    new_value = new_val.to_s
    new_prices = []
    Product.find(params[:productid]) do |product|
      product.price2.each do |price|
        new_prices << new_value
      end
    end
    Product.update(params[:productid], :price2 => new_prices)
  end

  def edit_cap
    new_val = '%.2f' % params[:new_val]
    new_value = new_val.to_s
    new_prices = []
    Product.find(params[:productid]) do |product|
      product.compare_at_price.each do |price|
        new_prices << new_value
      end
    end
    Product.update(params[:productid], :compare_at_price => new_prices)
  end
  
  def multiply_price
    multiplier = params[:new_val].to_f
    new_prices = []
    aaa = params[:productid];
    
    Product.all.each do |product|
        if product.id==aaa.to_i
          product.price.each do |price|
            prc = price.to_f * multiplier
            new_prices << prc
          end
        end
    end
    Product.update(params[:productid], :price2 => new_prices)
    respond_to do |format|
      format.html 
      format.js
    end
  end

  def multiply_cap
    multiplier = params[:new_val].to_f
    new_prices = []
    aaa = params[:productid];
    Product.all.each do |product|
        if product.id==aaa.to_i
          product.price.each do |price|
            prc = price.to_f * multiplier
            new_prices << prc
          end
        end
    end
    Product.update(params[:productid], :compare_at_price => new_prices)
    respond_to do |format|
      format.html
      format.js
    end

  end
  
  # push to store action
  def push
    shop_url = "https://2d69dfd97a185d97d49cb4b85de5e76f:1cd78cc392fe8861b891a3f881b3c5d8@gels-store.myshopify.com/admin"
    ShopifyAPI::Base.site = shop_url
    shop = ShopifyAPI::Shop.current
   
    options = []
    option = ShopifyAPI::Option.new(:name => "Color")
    options << option
    option1 = ShopifyAPI::Option.new(:name => "Size")
    options << option1
    
    variantsid = params[:check_var]
    _color = params[:_color]
    _size = params[:_size]
    _sku = params[:_sku]
    _prc = params[:_prc2]
    _cap = params[:_compAtPrice]
    _qty = params[:_qty]

    markup = Markup.find(2)
    price_markup = markup.price
    
    variants = []
    variantsid.each do |variant|
      zzz = ShopifyAPI::Variant.new( 
        :price                => _prc[variant.to_i],
        :option1              => _color[variant.to_i].gsub('_', ' '),
        :option2              => _size[variant.to_i].gsub('_', ' '),   
        :compare_at_price     => _cap[variant.to_i],
        :sku                  => _sku[variant.to_i],
        :inventory_management => "shopify",
        :inventory_quantity   => _qty[variant.to_i]
      )
      variants << zzz
    end
    
    new_product = ShopifyAPI::Product.new
    new_product.title = params[:_title]
    new_product.body_html = params[:content].gsub('&nbsp;', '').gsub('/','\/')
    new_product.product_type = params[:_type]
    new_product.vendor = params[:_vendor]
    new_product.tags = params[:_tags]
    new_product.options = options
    new_product.variants = variants
    new_product.metafields = [{:key => params[:mf_key],:value => params[:ae_url],:value_type => "string",:namespace => "imported-item" }]
    
    pao = []
    color2 =[]     #tempo storage
    aaa = 0 
    ctr = 0 
    
    _varimg = params[:_varimg]
    
    if _color.size==0
      variantsid.each do |row|
        color2 = []
        color2 << new_product.variants[ctr].id
        ctr = ctr + 1
      end
      pao << { id: nil, variant_ids: color2, src: default_img[0] }
    else
      gel = ''
      color2 = []
      lastvarimg = ''
      variantsid.each do |row|
        if gel==''
          gel = _varimg[row.to_i]
          color2 << new_product.variants[ctr].id
             
        elsif gel!=_varimg[row.to_i]
          pao << { id: nil, variant_ids: color2, src: lastvarimg }
          gel = _varimg[row.to_i]
          color2 = []
          color2 << new_product.variants[ctr].id
        else
          color2 << new_product.variants[ctr].id
       end
        lastvarimg =  _varimg[row.to_i]
        ctr = ctr+1
      end
      pao << { id: nil, variant_ids: color2, src: lastvarimg }      
    end
    
    new_product.images = pao
    new_product.save 
    
      collection = params[:collection]
      custom = ShopifyAPI::CustomCollection.find(:all, :params => { :title => collection })
      coll_id = custom[0].id
      new_product.add_to_collection(ShopifyAPI::CustomCollection.find(coll_id))
    
  end
  
  def remove_all
    Product.delete_all

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'All imports were deleted.' }
    end
  end
  
  def push_all
    Product.all.each do |product|
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :body_html, :images, :product_type, :tags, :vendor)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body_html %>
    <%= f.text_area :body_html %>
  </div>

  <div class="field">
    <%= f.label :images %>
    <%= f.text_field :images %>
  </div>

  <div class="field">
    <%= f.label :product_type %>
    <%= f.text_area :product_type %>
  </div>

  <div class="field">
    <%= f.label :tags %>
    <%= f.text_area :tags %>
  </div>

  <div class="field">
    <%= f.label :vendor %>
    <%= f.text_area :vendor %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/order.html.erb
<html>
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "Order Lists",
        icon: "<%= asset_path('favicon.ico') %>"
      });
    });

  </script>
  
<% end %>

<head>
  <style type="text/css">
    .Row {
      display: table;
      width: 100%; /*Optional*/
      table-layout: fixed; /*Optional*/
      border-spacing: 1px; /*Optional*/
      margin-top: 10px;
    }
    .Column {
      display: table-cell;
      width: 300px;
    }
    .Column2 {
      display: table-cell;
      float: right;
    }
  </style>

</head>

<div><p id="notice"><%= notice %></p></div>

<body style="background-color: #f2f2f2">

<nav class="navbar navbar-default navbar-fixed-top" style="height: 20px;">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <img alt="Brand" class="navbar-brand" href="#" src="https://simplesharebuttons.com/images/somacro/buffer.png"><a class="navbar-brand" style="font-family: Georgia, serif; color: black;">Uberlo</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><strong>Orders</strong></a></li>
      </ul>
    </div>
  </div>
</nav>
<br/>

<div class="col-lg-12" style="margin-top: 50px;">
  <div class="panel panel-primary">
    <!-- Default panel contents -->
    <div class="panel-heading" style="background-color: #ADD8E6;"><strong>Orders List!</strong></div>
    <div class="panel-body">
      <p>This section is for list of orders.</p>
    </div> 
  </div>
</div>

<div class="col-md-12" style="margin: auto;">

    <div class="col-md-12" style="background-color: #ADD8E6; margin: auto;">
      <form class="navbar-form navbar-left" role="search" style=" margin-right: 15%; margin-left: 15%;">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Enter Keywords" style="width: 582px; color: black;">
        </div>
        <button type="submit" class="btn btn-success" style="margin-left: 10px;  margin-right: 10px; width: 100px">Filter</button>

        <input type="text" data-provide='datepicker' style="margin-left: 10px; margin-right: 10px;"> - <input type="text" data-provide='datepicker' style="margin-left: 10px; margin-right: 10px;">
        <div class="btn-group" style="margin-left: 10px; margin-right: 10px;">
          <a href="#" class="btn btn-default">Select Date Range</a>
          <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </div>
      </form>
    </div>

    <div class="col-md-12" style="background-color: #ADD8E6;">
      <form class="navbar-form navbar-left" style=" margin-right: 15%; margin-left: 15%;">
        <div class="btn-group">
          <a href="#" class="btn btn-default" style="width: 218px;">Fulfillment Status: All</a>
          <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu" style="margin-left: 10px;">
            <li><input type="checkbox" name="vehicle" value="Bike">Unknown</li>
            <li><input type="checkbox" name="vehicle" value="Bike">Fulfilled</li>
            <li><input type="checkbox" name="vehicle" value="Bike">Unfulfilled</li>
            <li><input type="checkbox" name="vehicle" value="Bike">Partial</li>
          </ul>
        </div>
        <div class="btn-group">
          <a href="#" class="btn btn-default" style="width: 218px;">Financial Status: All</a>
          <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </div>
        <div class="btn-group">
          <a href="#" class="btn btn-default" style="width: 218px;">Flags Status: All</a>
          <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </div>
        <div class="btn-group">
          <a href="#" class="btn btn-default" style="width: 218px;">Order Status: All</a>
          <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </div>
        <div class="btn-group">
          <a href="#" class="btn btn-default" style="width: 218px;">Sources Status: All</a>
          <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </div>
      </form>
    </div>


<!--nav-->
  <div class="col-md-12">
    <div class="panel-body" style=" margin-top: 50px; margin-right: 15%; margin-left: 12.5%; color: #000; background-color: #ffffff;">
      <div id="myTabContent" class="tab-content">
        <div class="container">
          <div class="Row">
            <div class="col-lg-3">Order <a href="#">#0000</a> 0000 00 00</div>
            <div class="col-lg-3">Customer: <a href="">Buyer Number 00001</a></div>
            <div class="col-lg-3">Add Note</div>
            <div class="Column2"><button type="button" class="btn btn-default">Mark as Shipped</button></div>
          </div>
          <hr>
          <div class="Row">
            <div class="col-lg-3"><span class="label label-warning" style="margin-right: 10px">To Order</span>Supplier: <a href="#">Warehouse #0001</a></div>
            <div class="col-lg-2">Ali Order No:<button type="button" class="btn btn-sm" style="margin-left: 20px;">Add</button></div>
            <div class="col-lg-3">Shipped:<b style="margin-left: 5px">0/1</b><button type="button" class="btn btn-sm" style="margin-left: 10px">Mark as Shipped</button></div>
            <div class="Column2"><button type="button" class="btn btn-default" style="background-color: orange; color: white;">Order Product</button></div>
          </div>
          <div style="margin: auto; margin-top: 25px">
            <div style="border:1px; display:inline-block; background-color: #f2f2f2; width: 1150px; height: 100px; margin-bottom: 10px">

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



<!--end navs-->
</div>

<!--as->

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="js/bootstrap.js"></script>
  <script src="js/bootstrap.min.js"></script>
</body>

</html>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Body html:</strong>
  <%= @product.body_html %>
</p>

<p>
  <strong>Images:</strong>
  <%= @product.images %>
</p>

<p>
  <strong>Product type:</strong>
  <%= @product.product_type %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @product.tags %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @product.vendor %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>